fix: remove unversioned imports from mod.ts
Otherwise, publishing to JSR failed.

  error[missing-constraint]: specifier 'jsr:@probitas/probitas' is missing a version constraint
  Error:    --> /home/runner/work/cli/cli/mod.ts:119:8
      |
  119 | import "jsr:@probitas/probitas"; // Ensure package is included in bundle
      |        ^^^^^^^^^^^^^^^^^^^^^^^^ the specifier
      |
      = hint: specify a version constraint for the specifier

    info: the specifier resolved to version 0.6.0 today, but will resolve to a different
    info: major version if one is published in the future and potentially break
    docs: https://jsr.io/go/missing-constraint

  error: Found 1 problem