fix: it seems `deno install` is needed to update the nix hash correctly
Otherwise `deno install --frozen` fails due to out-of-date lockfile.

  error: The lockfile is out of date. Run `deno install --frozen=false`, or rerun with `--frozen=false` to update it.
  changes:
  104 | -    "@logtape/logtape@1.3.5": {
  104 | +    "@lambdalisue/sandbox@3.0.1": {
  105 | +      "integrity": "0735e8b101daccf673543d2cd77074900fcc5f63eb2306f52ca09539463bcac8"
  106 | +    },
  107 | +    "@logtape/logtape@1.3.5": {